name: 'Perl::Critic'
description: 'Run Perl::Critic against your Perl code'
inputs:
  files:
    description: 'Files to criticize'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/natanlao/critic:1.1'
  args:
    - ${{ inputs.files }}