name: 'Perl::Critic'
description: 'Run Perl::Critic against your Perl code'
inputs:
  files:
    description: 'Files to criticize'
    required: false
runs:
  using: 'docker'
  # TODO: The image is built and published to GitHub Packages on tags, and
  # it would be faster to use that image. Blocked on GitHub Actions requiring
  # auth to download public images. (See also actions/starter-workflows#66)
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}