#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use version; our $VERSION = qv('1.0.0');

use Perl::Critic;
use Cwd qw(cwd);

my @files;
if ( scalar @ARGV > 0 ) {
    foreach my $arg (@ARGV) {
        if ( -d $arg ) {
            push @files, Perl::Critic::Utils::all_perl_files( cwd() );
        }
        elsif ( -e $arg ) {
            push @files, $arg;
        }
        else {
            print "::warning file=$arg,line=0,col=0::File not found\n";
        }
    }
}
else {
    @files = Perl::Critic::Utils::all_perl_files( cwd() );
}

my $critic = Perl::Critic->new();
my $vcount = 0;
foreach my $file (@files) {
    foreach my $violation ( $critic->critique($file) ) {
        $vcount++;
        my $row = $violation->line_number();
        my $col = $violation->column_number();
        my $dsc = $violation->description();
        print "::error file=$file,line=$row,col=${col}::$violation";
    }
}

exit( $vcount > 0 );
