#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use version; our $VERSION = qv('1.0.0');

use Perl::Critic;
use Perl::Critic::Utils;
use Cwd qw(abs_path cwd);

# Analyse all perl files below the current directory.
my $critic = Perl::Critic->new();
my @files  = $ARGV || Perl::Critic::Utils::all_perl_files( cwd() );
my $vcount = 0;
foreach my $file (@files) {
    foreach my $violation ( $critic->critique($file) ) {
        $vcount++;
        my $row = $violation->line_number();
        my $col = $violation->column_number();
        my $dsc = $violation->description();
        print "::error file=$file,line=$row,col=${col}::$violation";
    }
}

exit( $vcount > 0 );
