on: [push]

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Perl::Critic
      uses: natanlao/docker-perl_critic@v1
      with:
        files: critic