on: [push]

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Perl::Critic
      uses: natanlao/perl-critic-action@develop
      with:
        files: critic